package com.gsccs.cms.auth.model;

import java.util.Date;

/**
 * 
 * @author x.d zhang
 *
 */
public class SysDict {
    
    private String id;
    private String code;
    private String name;
    private Integer sort;
    private String type;
    private String iconcls;
    private String state;
    private Integer permissionid;
    private String parentId;
    private String description;
    private String status;
    private Date created;
    private Date lastmod;
    private String creater;
    private String modifyer;

    public String getId() {
        return id;
    }

    
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

   
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.CODE
     *
     * @param code the value for sys_dict.CODE
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.NAME
     *
     * @return the value of sys_dict.NAME
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.NAME
     *
     * @param name the value for sys_dict.NAME
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.SORT
     *
     * @return the value of sys_dict.SORT
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.SORT
     *
     * @param sort the value for sys_dict.SORT
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.TYPE
     *
     * @return the value of sys_dict.TYPE
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.TYPE
     *
     * @param type the value for sys_dict.TYPE
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.ICONCLS
     *
     * @return the value of sys_dict.ICONCLS
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public String getIconcls() {
        return iconcls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.ICONCLS
     *
     * @param iconcls the value for sys_dict.ICONCLS
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public void setIconcls(String iconcls) {
        this.iconcls = iconcls == null ? null : iconcls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.STATE
     *
     * @return the value of sys_dict.STATE
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.STATE
     *
     * @param state the value for sys_dict.STATE
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.PERMISSIONID
     *
     * @return the value of sys_dict.PERMISSIONID
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public Integer getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.PERMISSIONID
     *
     * @param permissionid the value for sys_dict.PERMISSIONID
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.PARENT_ID
     *
     * @return the value of sys_dict.PARENT_ID
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.PARENT_ID
     *
     * @param parentId the value for sys_dict.PARENT_ID
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.DESCRIPTION
     *
     * @return the value of sys_dict.DESCRIPTION
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.DESCRIPTION
     *
     * @param description the value for sys_dict.DESCRIPTION
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.STATUS
     *
     * @return the value of sys_dict.STATUS
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.STATUS
     *
     * @param status the value for sys_dict.STATUS
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.CREATED
     *
     * @return the value of sys_dict.CREATED
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.CREATED
     *
     * @param created the value for sys_dict.CREATED
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.LASTMOD
     *
     * @return the value of sys_dict.LASTMOD
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public Date getLastmod() {
        return lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.LASTMOD
     *
     * @param lastmod the value for sys_dict.LASTMOD
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public void setLastmod(Date lastmod) {
        this.lastmod = lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.CREATER
     *
     * @return the value of sys_dict.CREATER
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.CREATER
     *
     * @param creater the value for sys_dict.CREATER
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.MODIFYER
     *
     * @return the value of sys_dict.MODIFYER
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public String getModifyer() {
        return modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.MODIFYER
     *
     * @param modifyer the value for sys_dict.MODIFYER
     *
     * @mbggenerated Thu May 01 21:32:37 CST 2014
     */
    public void setModifyer(String modifyer) {
        this.modifyer = modifyer == null ? null : modifyer.trim();
    }
}