package com.gsccs.cms.core.model;

public class ContentImg {
    
    private String id;

    
    private String infoid;

    
    private String img;

    
    private String title;

    
    private String content;

    
    private Integer ordernum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_img.id
     *
     * @return the value of cms_article_img.id
     *
     * @mbggenerated Wed Jul 03 17:29:37 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_img.id
     *
     * @param id the value for cms_article_img.id
     *
     * @mbggenerated Wed Jul 03 17:29:37 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_img.infoid
     *
     * @return the value of cms_article_img.infoid
     *
     * @mbggenerated Wed Jul 03 17:29:37 CST 2013
     */
    public String getInfoid() {
        return infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_img.infoid
     *
     * @param infoid the value for cms_article_img.infoid
     *
     * @mbggenerated Wed Jul 03 17:29:37 CST 2013
     */
    public void setInfoid(String infoid) {
        this.infoid = infoid == null ? null : infoid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_img.img
     *
     * @return the value of cms_article_img.img
     *
     * @mbggenerated Wed Jul 03 17:29:37 CST 2013
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_img.img
     *
     * @param img the value for cms_article_img.img
     *
     * @mbggenerated Wed Jul 03 17:29:37 CST 2013
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_img.title
     *
     * @return the value of cms_article_img.title
     *
     * @mbggenerated Wed Jul 03 17:29:37 CST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_img.title
     *
     * @param title the value for cms_article_img.title
     *
     * @mbggenerated Wed Jul 03 17:29:37 CST 2013
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_img.content
     *
     * @return the value of cms_article_img.content
     *
     * @mbggenerated Wed Jul 03 17:29:37 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_img.content
     *
     * @param content the value for cms_article_img.content
     *
     * @mbggenerated Wed Jul 03 17:29:37 CST 2013
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_img.ordernum
     *
     * @return the value of cms_article_img.ordernum
     *
     * @mbggenerated Wed Jul 03 17:29:37 CST 2013
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_img.ordernum
     *
     * @param ordernum the value for cms_article_img.ordernum
     *
     * @mbggenerated Wed Jul 03 17:29:37 CST 2013
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }
}