package com.gsccs.cms.auth.model;

public class RoleOper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_oper.id
     *
     * @mbggenerated Tue Mar 25 17:59:32 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_oper.roleId
     *
     * @mbggenerated Tue Mar 25 17:59:32 CST 2014
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_oper.operId
     *
     * @mbggenerated Tue Mar 25 17:59:32 CST 2014
     */
    private String operid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_oper.id
     *
     * @return the value of sys_role_oper.id
     *
     * @mbggenerated Tue Mar 25 17:59:32 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_oper.id
     *
     * @param id the value for sys_role_oper.id
     *
     * @mbggenerated Tue Mar 25 17:59:32 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_oper.roleId
     *
     * @return the value of sys_role_oper.roleId
     *
     * @mbggenerated Tue Mar 25 17:59:32 CST 2014
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_oper.roleId
     *
     * @param roleid the value for sys_role_oper.roleId
     *
     * @mbggenerated Tue Mar 25 17:59:32 CST 2014
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_oper.operId
     *
     * @return the value of sys_role_oper.operId
     *
     * @mbggenerated Tue Mar 25 17:59:32 CST 2014
     */
    public String getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_oper.operId
     *
     * @param operid the value for sys_role_oper.operId
     *
     * @mbggenerated Tue Mar 25 17:59:32 CST 2014
     */
    public void setOperid(String operid) {
        this.operid = operid == null ? null : operid.trim();
    }
}