package com.gsccs.cms.core.model;

public class TempletChannel {
    
    private String id;

    private String hasChildren;
    public static String STATE_EFFECTIVE="1";
    public static String STATE_INVALID="0";
    public static String NAVIGATION_YES="1";
    public static String NAVIGATION_NO="0";
    private String navigationStr;
    private String stateStr;
    
    private String name;

    
    private String templet;

    
    private String contenttemplet;

    
    private String img;

    
    private String parid;

    
    private String site;

    
    private String url;

    
    private String state;

    
    private Integer ordernum;

    
    private Integer clicknum;

    
    private String navigation;

    
    private String pagemark;

    
    private String htmlchannel;

    
    private String htmlchannelold;

    
    private String htmlparchannel;

    
    private String htmlsite;

    
    private String templetid;
    private String sql;

    
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.id
     *
     * @return the value of cms_templet_channel.id
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.id
     *
     * @param id the value for cms_templet_channel.id
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.name
     *
     * @return the value of cms_templet_channel.name
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.name
     *
     * @param name the value for cms_templet_channel.name
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.templet
     *
     * @return the value of cms_templet_channel.templet
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getTemplet() {
        return templet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.templet
     *
     * @param templet the value for cms_templet_channel.templet
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setTemplet(String templet) {
        this.templet = templet == null ? null : templet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.contentTemplet
     *
     * @return the value of cms_templet_channel.contentTemplet
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getContenttemplet() {
        return contenttemplet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.contentTemplet
     *
     * @param contenttemplet the value for cms_templet_channel.contentTemplet
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setContenttemplet(String contenttemplet) {
        this.contenttemplet = contenttemplet == null ? null : contenttemplet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.img
     *
     * @return the value of cms_templet_channel.img
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.img
     *
     * @param img the value for cms_templet_channel.img
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.parId
     *
     * @return the value of cms_templet_channel.parId
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getParid() {
        return parid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.parId
     *
     * @param parid the value for cms_templet_channel.parId
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setParid(String parid) {
        this.parid = parid == null ? null : parid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.site
     *
     * @return the value of cms_templet_channel.site
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.site
     *
     * @param site the value for cms_templet_channel.site
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.url
     *
     * @return the value of cms_templet_channel.url
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.url
     *
     * @param url the value for cms_templet_channel.url
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.state
     *
     * @return the value of cms_templet_channel.state
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.state
     *
     * @param state the value for cms_templet_channel.state
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.orderNum
     *
     * @return the value of cms_templet_channel.orderNum
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.orderNum
     *
     * @param ordernum the value for cms_templet_channel.orderNum
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.clickNum
     *
     * @return the value of cms_templet_channel.clickNum
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public Integer getClicknum() {
        return clicknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.clickNum
     *
     * @param clicknum the value for cms_templet_channel.clickNum
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setClicknum(Integer clicknum) {
        this.clicknum = clicknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.navigation
     *
     * @return the value of cms_templet_channel.navigation
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getNavigation() {
        return navigation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.navigation
     *
     * @param navigation the value for cms_templet_channel.navigation
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setNavigation(String navigation) {
        this.navigation = navigation == null ? null : navigation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.pagemark
     *
     * @return the value of cms_templet_channel.pagemark
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getPagemark() {
        return pagemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.pagemark
     *
     * @param pagemark the value for cms_templet_channel.pagemark
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setPagemark(String pagemark) {
        this.pagemark = pagemark == null ? null : pagemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.htmlChannel
     *
     * @return the value of cms_templet_channel.htmlChannel
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getHtmlchannel() {
        return htmlchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.htmlChannel
     *
     * @param htmlchannel the value for cms_templet_channel.htmlChannel
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setHtmlchannel(String htmlchannel) {
        this.htmlchannel = htmlchannel == null ? null : htmlchannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.htmlChannelOld
     *
     * @return the value of cms_templet_channel.htmlChannelOld
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getHtmlchannelold() {
        return htmlchannelold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.htmlChannelOld
     *
     * @param htmlchannelold the value for cms_templet_channel.htmlChannelOld
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setHtmlchannelold(String htmlchannelold) {
        this.htmlchannelold = htmlchannelold == null ? null : htmlchannelold.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.htmlParchannel
     *
     * @return the value of cms_templet_channel.htmlParchannel
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getHtmlparchannel() {
        return htmlparchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.htmlParchannel
     *
     * @param htmlparchannel the value for cms_templet_channel.htmlParchannel
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setHtmlparchannel(String htmlparchannel) {
        this.htmlparchannel = htmlparchannel == null ? null : htmlparchannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.htmlSite
     *
     * @return the value of cms_templet_channel.htmlSite
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getHtmlsite() {
        return htmlsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.htmlSite
     *
     * @param htmlsite the value for cms_templet_channel.htmlSite
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setHtmlsite(String htmlsite) {
        this.htmlsite = htmlsite == null ? null : htmlsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.templetid
     *
     * @return the value of cms_templet_channel.templetid
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getTempletid() {
        return templetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.templetid
     *
     * @param templetid the value for cms_templet_channel.templetid
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setTempletid(String templetid) {
        this.templetid = templetid == null ? null : templetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_templet_channel.description
     *
     * @return the value of cms_templet_channel.description
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_templet_channel.description
     *
     * @param description the value for cms_templet_channel.description
     *
     * @mbggenerated Tue May 07 20:54:47 CST 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

	public String getHasChildren() {
		return hasChildren;
	}

	public void setHasChildren(String hasChildren) {
		this.hasChildren = hasChildren;
	}

	public String getSql() {
		return sql;
	}

	public void setSql(String sql) {
		this.sql = sql;
	}
	public String getStateStr() {
		stateStr="是";
		if (STATE_INVALID.equals(state)) {
			stateStr="否";
		}
		return stateStr;
	}

	public void setStateStr(String stateStr) {
		this.stateStr = stateStr;
	}

	public String getNavigationStr() {
		navigationStr="是";
		if (NAVIGATION_NO.equals(navigation)) {
			navigationStr="否";
		}
		return navigationStr;
	}

	public void setNavigationStr(String navigationStr) {
		this.navigationStr = navigationStr;
	}
}