package com.gsccs.cms.auth.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.gsccs.cms.auth.model.RoleUser;
import com.gsccs.cms.auth.model.RoleUserExample;

public interface RoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2013
     */
    int countByExample(RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2013
     */
    int deleteByExample(RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2013
     */
    int insert(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2013
     */
    int insertSelective(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2013
     */
    List<RoleUser> selectByExample(RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2013
     */
    RoleUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2013
     */
    int updateByExampleSelective(@Param("record") RoleUser record, @Param("example") RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2013
     */
    int updateByExample(@Param("record") RoleUser record, @Param("example") RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2013
     */
    int updateByPrimaryKeySelective(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2013
     */
    int updateByPrimaryKey(RoleUser record);
}