package com.gsccs.cms.auth.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.gsccs.cms.auth.model.UnitUser;
import com.gsccs.cms.auth.model.UnitUserExample;


public interface UnitUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_user
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2013
     */
    int countByExample(UnitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_user
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2013
     */
    int deleteByExample(UnitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_user
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_user
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2013
     */
    int insert(UnitUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_user
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2013
     */
    int insertSelective(UnitUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_user
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2013
     */
    List<UnitUser> selectByExample(UnitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_user
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2013
     */
    UnitUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_user
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2013
     */
    int updateByExampleSelective(@Param("record") UnitUser record, @Param("example") UnitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_user
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2013
     */
    int updateByExample(@Param("record") UnitUser record, @Param("example") UnitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_user
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2013
     */
    int updateByPrimaryKeySelective(UnitUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_user
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2013
     */
    int updateByPrimaryKey(UnitUser record);
}