package com.gsccs.cms.auth.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.gsccs.cms.auth.model.Roles;
import com.gsccs.cms.auth.model.RolesExample;

public interface RolesMapper {

	int countByExample(RolesExample example);

	List<Roles> selectPageByExample(RolesExample example);

	int deleteByExample(RolesExample example);

	int deleteByPrimaryKey(String id);

	int insert(Roles record);

	int insertSelective(Roles record);

	List<Roles> selectByExample(RolesExample example);

	Roles selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table roles
	 *
	 * @mbggenerated Fri Dec 16 16:07:41 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Roles record,
			@Param("example") RolesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table roles
	 *
	 * @mbggenerated Fri Dec 16 16:07:41 CST 2013
	 */
	int updateByExample(@Param("record") Roles record,
			@Param("example") RolesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table roles
	 *
	 * @mbggenerated Fri Dec 16 16:07:41 CST 2013
	 */
	int updateByPrimaryKeySelective(Roles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table roles
	 *
	 * @mbggenerated Fri Dec 16 16:07:41 CST 2013
	 */
	int updateByPrimaryKey(Roles record);
}