package com.gsccs.cms.core.model;

import java.io.Serializable;

public class Sensitive implements Serializable{
    
    private String id;

    
    private String sensitiveword;

    
    private String replaceto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sensitive.id
     *
     * @return the value of cms_sensitive.id
     *
     * @mbggenerated Sun Apr 28 15:41:01 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sensitive.id
     *
     * @param id the value for cms_sensitive.id
     *
     * @mbggenerated Sun Apr 28 15:41:01 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sensitive.sensitiveword
     *
     * @return the value of cms_sensitive.sensitiveword
     *
     * @mbggenerated Sun Apr 28 15:41:01 CST 2013
     */
    public String getSensitiveword() {
        return sensitiveword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sensitive.sensitiveword
     *
     * @param sensitiveword the value for cms_sensitive.sensitiveword
     *
     * @mbggenerated Sun Apr 28 15:41:01 CST 2013
     */
    public void setSensitiveword(String sensitiveword) {
        this.sensitiveword = sensitiveword == null ? null : sensitiveword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_sensitive.replaceto
     *
     * @return the value of cms_sensitive.replaceto
     *
     * @mbggenerated Sun Apr 28 15:41:01 CST 2013
     */
    public String getReplaceto() {
        return replaceto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_sensitive.replaceto
     *
     * @param replaceto the value for cms_sensitive.replaceto
     *
     * @mbggenerated Sun Apr 28 15:41:01 CST 2013
     */
    public void setReplaceto(String replaceto) {
        this.replaceto = replaceto == null ? null : replaceto.trim();
    }
}